### ISSUE TITLE
if you are so blatantly copying my work - I would at least appreciate an acknowledgement or credit section.

### ISSUE THREAD

**Issue by hangukquant** [createMonster/Multi-Strategy-Quant-System#8]

**Comment by createMonster** [comment]
Hi sir

I followed along your course and use the code base for trying out my own strategies. Your course is great and i have no intention to distribute your work to others for profit. Will add a acknowledgement section later. 

Sorry for any inconveniences caused, and wish you have a good day.

**Comment by createMonster** [comment]
PS the readme was generated by chatgpt

**Comment by hangukquant** [comment]
I understand - but an MIT license you listed is the opposite of that: https://opensource.org/license/mit/.
You do not have the right to distribute my work, for profit or non-profit. Of course, you can use it for your own research.

It is alright - I believe it is an honest mistake, so I am going to just consider everything settled and not poke further. Be careful about other projects, other people might not have similar attitudes towards sharing of their work.
